<template>
  <q-page class="q-pa-lg">
    <h4 class="q-mt-none q-mb-md text-weight-bold">About</h4>
    <div class="text-body1">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam
        fringilla nisl in nulla sodales, vel consectetur dui maximus. Ut
        vulputate odio lorem, ut congue diam laoreet laoreet. Quisque id
        efficitur nibh, vitae ullamcorper libero. Nam id tortor sodales,
        bibendum urna sit amet, varius nisl. Pellentesque congue, massa quis
        eleifend finibus, libero lacus commodo ipsum, a commodo velit massa ut
        risus. Vestibulum risus orci, efficitur nec nulla et, accumsan congue
        nibh. Sed enim lectus, vestibulum quis augue sed, pretium molestie leo.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
        hendrerit libero id blandit dapibus. Fusce cursus nisl mauris, mollis
        molestie nisi imperdiet quis. Vestibulum at luctus elit, sit amet
        commodo nulla.
      </p>

      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam
        fringilla nisl in nulla sodales, vel consectetur dui maximus. Ut
        vulputate odio lorem, ut congue diam laoreet laoreet. Quisque id
        efficitur nibh, vitae ullamcorper libero. Nam id tortor sodales,
        bibendum urna sit amet, varius nisl. Pellentesque congue, massa quis
        eleifend finibus, libero lacus commodo ipsum, a commodo velit massa ut
        risus. Vestibulum risus orci, efficitur nec nulla et, accumsan congue
        nibh. Sed enim lectus, vestibulum quis augue sed, pretium molestie leo.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
        hendrerit libero id blandit dapibus. Fusce cursus nisl mauris, mollis
        molestie nisi imperdiet quis. Vestibulum at luctus elit, sit amet
        commodo nulla.
      </p>
    </div>
  </q-page>
</template>

<script>
export default {
  name: "PageAbout"
};
</script>
